<?php
/**
 * DynamicTemplatesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Paubox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paubox Email API
 *
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Paubox\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Paubox\ApiException;
use Paubox\Configuration;
use Paubox\FormDataProcessor;
use Paubox\HeaderSelector;
use Paubox\ObjectSerializer;

/**
 * DynamicTemplatesApi Class Doc Comment
 *
 * @category Class
 * @package  Paubox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DynamicTemplatesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createDynamicTemplate' => [
            'multipart/form-data',
        ],
        'deleteDynamicTemplate' => [
            'application/json',
        ],
        'getDynamicTemplate' => [
            'application/json',
        ],
        'listDynamicTemplates' => [
            'application/json',
        ],
        'sendTemplatedMessage' => [
            'application/json',
        ],
        'updateDynamicTemplate' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createDynamicTemplate
     *
     * Create a dynamic template
     *
     * @param  string $data_name Name for the template (required)
     * @param  \SplFileObject $data_body Handlebars template file (.hbs) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paubox\Model\DynamicTemplateResponse|\Paubox\Model\ErrorResponse
     */
    public function createDynamicTemplate($data_name, $data_body, string $contentType = self::contentTypes['createDynamicTemplate'][0])
    {
        list($response) = $this->createDynamicTemplateWithHttpInfo($data_name, $data_body, $contentType);
        return $response;
    }

    /**
     * Operation createDynamicTemplateWithHttpInfo
     *
     * Create a dynamic template
     *
     * @param  string $data_name Name for the template (required)
     * @param  \SplFileObject $data_body Handlebars template file (.hbs) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paubox\Model\DynamicTemplateResponse|\Paubox\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createDynamicTemplateWithHttpInfo($data_name, $data_body, string $contentType = self::contentTypes['createDynamicTemplate'][0])
    {
        $request = $this->createDynamicTemplateRequest($data_name, $data_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\DynamicTemplateResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paubox\Model\DynamicTemplateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\DynamicTemplateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createDynamicTemplateAsync
     *
     * Create a dynamic template
     *
     * @param  string $data_name Name for the template (required)
     * @param  \SplFileObject $data_body Handlebars template file (.hbs) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createDynamicTemplateAsync($data_name, $data_body, string $contentType = self::contentTypes['createDynamicTemplate'][0])
    {
        return $this->createDynamicTemplateAsyncWithHttpInfo($data_name, $data_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createDynamicTemplateAsyncWithHttpInfo
     *
     * Create a dynamic template
     *
     * @param  string $data_name Name for the template (required)
     * @param  \SplFileObject $data_body Handlebars template file (.hbs) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createDynamicTemplateAsyncWithHttpInfo($data_name, $data_body, string $contentType = self::contentTypes['createDynamicTemplate'][0])
    {
        $returnType = '\Paubox\Model\DynamicTemplateResponse';
        $request = $this->createDynamicTemplateRequest($data_name, $data_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createDynamicTemplate'
     *
     * @param  string $data_name Name for the template (required)
     * @param  \SplFileObject $data_body Handlebars template file (.hbs) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createDynamicTemplateRequest($data_name, $data_body, string $contentType = self::contentTypes['createDynamicTemplate'][0])
    {

        // verify the required parameter 'data_name' is set
        if ($data_name === null || (is_array($data_name) && count($data_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data_name when calling createDynamicTemplate'
            );
        }

        // verify the required parameter 'data_body' is set
        if ($data_body === null || (is_array($data_body) && count($data_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data_body when calling createDynamicTemplate'
            );
        }


        $resourcePath = '/dynamic_templates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'data_name' => $data_name,
            'data_body' => $data_body,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteDynamicTemplate
     *
     * Delete a dynamic template
     *
     * @param  string $id Template ID to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paubox\Model\DeleteDynamicTemplate200Response|\Paubox\Model\ErrorResponse
     */
    public function deleteDynamicTemplate($id, string $contentType = self::contentTypes['deleteDynamicTemplate'][0])
    {
        list($response) = $this->deleteDynamicTemplateWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation deleteDynamicTemplateWithHttpInfo
     *
     * Delete a dynamic template
     *
     * @param  string $id Template ID to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paubox\Model\DeleteDynamicTemplate200Response|\Paubox\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteDynamicTemplateWithHttpInfo($id, string $contentType = self::contentTypes['deleteDynamicTemplate'][0])
    {
        $request = $this->deleteDynamicTemplateRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\DeleteDynamicTemplate200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paubox\Model\DeleteDynamicTemplate200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\DeleteDynamicTemplate200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteDynamicTemplateAsync
     *
     * Delete a dynamic template
     *
     * @param  string $id Template ID to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteDynamicTemplateAsync($id, string $contentType = self::contentTypes['deleteDynamicTemplate'][0])
    {
        return $this->deleteDynamicTemplateAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteDynamicTemplateAsyncWithHttpInfo
     *
     * Delete a dynamic template
     *
     * @param  string $id Template ID to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteDynamicTemplateAsyncWithHttpInfo($id, string $contentType = self::contentTypes['deleteDynamicTemplate'][0])
    {
        $returnType = '\Paubox\Model\DeleteDynamicTemplate200Response';
        $request = $this->deleteDynamicTemplateRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteDynamicTemplate'
     *
     * @param  string $id Template ID to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteDynamicTemplateRequest($id, string $contentType = self::contentTypes['deleteDynamicTemplate'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteDynamicTemplate'
            );
        }


        $resourcePath = '/dynamic_templates/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDynamicTemplate
     *
     * Get a dynamic template
     *
     * @param  string $id Template ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paubox\Model\DynamicTemplateResponse|\Paubox\Model\ErrorResponse
     */
    public function getDynamicTemplate($id, string $contentType = self::contentTypes['getDynamicTemplate'][0])
    {
        list($response) = $this->getDynamicTemplateWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getDynamicTemplateWithHttpInfo
     *
     * Get a dynamic template
     *
     * @param  string $id Template ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paubox\Model\DynamicTemplateResponse|\Paubox\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDynamicTemplateWithHttpInfo($id, string $contentType = self::contentTypes['getDynamicTemplate'][0])
    {
        $request = $this->getDynamicTemplateRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\DynamicTemplateResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paubox\Model\DynamicTemplateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\DynamicTemplateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDynamicTemplateAsync
     *
     * Get a dynamic template
     *
     * @param  string $id Template ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDynamicTemplateAsync($id, string $contentType = self::contentTypes['getDynamicTemplate'][0])
    {
        return $this->getDynamicTemplateAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDynamicTemplateAsyncWithHttpInfo
     *
     * Get a dynamic template
     *
     * @param  string $id Template ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDynamicTemplateAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getDynamicTemplate'][0])
    {
        $returnType = '\Paubox\Model\DynamicTemplateResponse';
        $request = $this->getDynamicTemplateRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDynamicTemplate'
     *
     * @param  string $id Template ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDynamicTemplateRequest($id, string $contentType = self::contentTypes['getDynamicTemplate'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getDynamicTemplate'
            );
        }


        $resourcePath = '/dynamic_templates/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listDynamicTemplates
     *
     * List all dynamic templates
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDynamicTemplates'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paubox\Model\DynamicTemplateListResponse|\Paubox\Model\ErrorResponse
     */
    public function listDynamicTemplates(string $contentType = self::contentTypes['listDynamicTemplates'][0])
    {
        list($response) = $this->listDynamicTemplatesWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation listDynamicTemplatesWithHttpInfo
     *
     * List all dynamic templates
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDynamicTemplates'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paubox\Model\DynamicTemplateListResponse|\Paubox\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listDynamicTemplatesWithHttpInfo(string $contentType = self::contentTypes['listDynamicTemplates'][0])
    {
        $request = $this->listDynamicTemplatesRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\DynamicTemplateListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paubox\Model\DynamicTemplateListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\DynamicTemplateListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listDynamicTemplatesAsync
     *
     * List all dynamic templates
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDynamicTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listDynamicTemplatesAsync(string $contentType = self::contentTypes['listDynamicTemplates'][0])
    {
        return $this->listDynamicTemplatesAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listDynamicTemplatesAsyncWithHttpInfo
     *
     * List all dynamic templates
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDynamicTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listDynamicTemplatesAsyncWithHttpInfo(string $contentType = self::contentTypes['listDynamicTemplates'][0])
    {
        $returnType = '\Paubox\Model\DynamicTemplateListResponse';
        $request = $this->listDynamicTemplatesRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listDynamicTemplates'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDynamicTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listDynamicTemplatesRequest(string $contentType = self::contentTypes['listDynamicTemplates'][0])
    {


        $resourcePath = '/dynamic_templates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendTemplatedMessage
     *
     * Send a dynamically templated message
     *
     * @param  \Paubox\Model\TemplatedMessageRequest $templated_message_request templated_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendTemplatedMessage'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paubox\Model\SingleSendResponse|\Paubox\Model\ErrorResponse
     */
    public function sendTemplatedMessage($templated_message_request, string $contentType = self::contentTypes['sendTemplatedMessage'][0])
    {
        list($response) = $this->sendTemplatedMessageWithHttpInfo($templated_message_request, $contentType);
        return $response;
    }

    /**
     * Operation sendTemplatedMessageWithHttpInfo
     *
     * Send a dynamically templated message
     *
     * @param  \Paubox\Model\TemplatedMessageRequest $templated_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendTemplatedMessage'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paubox\Model\SingleSendResponse|\Paubox\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendTemplatedMessageWithHttpInfo($templated_message_request, string $contentType = self::contentTypes['sendTemplatedMessage'][0])
    {
        $request = $this->sendTemplatedMessageRequest($templated_message_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\SingleSendResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paubox\Model\SingleSendResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\SingleSendResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation sendTemplatedMessageAsync
     *
     * Send a dynamically templated message
     *
     * @param  \Paubox\Model\TemplatedMessageRequest $templated_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendTemplatedMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendTemplatedMessageAsync($templated_message_request, string $contentType = self::contentTypes['sendTemplatedMessage'][0])
    {
        return $this->sendTemplatedMessageAsyncWithHttpInfo($templated_message_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendTemplatedMessageAsyncWithHttpInfo
     *
     * Send a dynamically templated message
     *
     * @param  \Paubox\Model\TemplatedMessageRequest $templated_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendTemplatedMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendTemplatedMessageAsyncWithHttpInfo($templated_message_request, string $contentType = self::contentTypes['sendTemplatedMessage'][0])
    {
        $returnType = '\Paubox\Model\SingleSendResponse';
        $request = $this->sendTemplatedMessageRequest($templated_message_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendTemplatedMessage'
     *
     * @param  \Paubox\Model\TemplatedMessageRequest $templated_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendTemplatedMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendTemplatedMessageRequest($templated_message_request, string $contentType = self::contentTypes['sendTemplatedMessage'][0])
    {

        // verify the required parameter 'templated_message_request' is set
        if ($templated_message_request === null || (is_array($templated_message_request) && count($templated_message_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $templated_message_request when calling sendTemplatedMessage'
            );
        }


        $resourcePath = '/templated_messages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($templated_message_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($templated_message_request));
            } else {
                $httpBody = $templated_message_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateDynamicTemplate
     *
     * Update a dynamic template
     *
     * @param  string $id Template ID to update (required)
     * @param  string|null $data_name Updated name for the template (optional)
     * @param  \SplFileObject|null $data_body Updated Handlebars template file (.hbs) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paubox\Model\DynamicTemplateResponse|\Paubox\Model\ErrorResponse|\Paubox\Model\ErrorResponse
     */
    public function updateDynamicTemplate($id, $data_name = null, $data_body = null, string $contentType = self::contentTypes['updateDynamicTemplate'][0])
    {
        list($response) = $this->updateDynamicTemplateWithHttpInfo($id, $data_name, $data_body, $contentType);
        return $response;
    }

    /**
     * Operation updateDynamicTemplateWithHttpInfo
     *
     * Update a dynamic template
     *
     * @param  string $id Template ID to update (required)
     * @param  string|null $data_name Updated name for the template (optional)
     * @param  \SplFileObject|null $data_body Updated Handlebars template file (.hbs) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \Paubox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paubox\Model\DynamicTemplateResponse|\Paubox\Model\ErrorResponse|\Paubox\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateDynamicTemplateWithHttpInfo($id, $data_name = null, $data_body = null, string $contentType = self::contentTypes['updateDynamicTemplate'][0])
    {
        $request = $this->updateDynamicTemplateRequest($id, $data_name, $data_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\DynamicTemplateResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Paubox\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paubox\Model\DynamicTemplateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\DynamicTemplateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paubox\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateDynamicTemplateAsync
     *
     * Update a dynamic template
     *
     * @param  string $id Template ID to update (required)
     * @param  string|null $data_name Updated name for the template (optional)
     * @param  \SplFileObject|null $data_body Updated Handlebars template file (.hbs) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateDynamicTemplateAsync($id, $data_name = null, $data_body = null, string $contentType = self::contentTypes['updateDynamicTemplate'][0])
    {
        return $this->updateDynamicTemplateAsyncWithHttpInfo($id, $data_name, $data_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateDynamicTemplateAsyncWithHttpInfo
     *
     * Update a dynamic template
     *
     * @param  string $id Template ID to update (required)
     * @param  string|null $data_name Updated name for the template (optional)
     * @param  \SplFileObject|null $data_body Updated Handlebars template file (.hbs) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateDynamicTemplateAsyncWithHttpInfo($id, $data_name = null, $data_body = null, string $contentType = self::contentTypes['updateDynamicTemplate'][0])
    {
        $returnType = '\Paubox\Model\DynamicTemplateResponse';
        $request = $this->updateDynamicTemplateRequest($id, $data_name, $data_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateDynamicTemplate'
     *
     * @param  string $id Template ID to update (required)
     * @param  string|null $data_name Updated name for the template (optional)
     * @param  \SplFileObject|null $data_body Updated Handlebars template file (.hbs) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDynamicTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateDynamicTemplateRequest($id, $data_name = null, $data_body = null, string $contentType = self::contentTypes['updateDynamicTemplate'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateDynamicTemplate'
            );
        }




        $resourcePath = '/dynamic_templates/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'data_name' => $data_name,
            'data_body' => $data_body,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
