<?php
/**
 * DeliveryStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Paubox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paubox Email API
 *
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Paubox\Model;

use \ArrayAccess;
use \Paubox\ObjectSerializer;

/**
 * DeliveryStatus Class Doc Comment
 *
 * @category Class
 * @package  Paubox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DeliveryStatus implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeliveryStatus';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'delivery_status' => 'string',
        'delivery_time' => 'string',
        'opened_status' => 'string',
        'opened_time' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'delivery_status' => null,
        'delivery_time' => null,
        'opened_status' => null,
        'opened_time' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'delivery_status' => false,
        'delivery_time' => false,
        'opened_status' => false,
        'opened_time' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'delivery_status' => 'deliveryStatus',
        'delivery_time' => 'deliveryTime',
        'opened_status' => 'openedStatus',
        'opened_time' => 'openedTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'delivery_status' => 'setDeliveryStatus',
        'delivery_time' => 'setDeliveryTime',
        'opened_status' => 'setOpenedStatus',
        'opened_time' => 'setOpenedTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'delivery_status' => 'getDeliveryStatus',
        'delivery_time' => 'getDeliveryTime',
        'opened_status' => 'getOpenedStatus',
        'opened_time' => 'getOpenedTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DELIVERY_STATUS_PROCESSING = 'processing';
    public const DELIVERY_STATUS_TLS_NOT_OFFERED_SENDING_VIA_SECURE_PORTAL = 'TLS not offered, sending via Secure Portal';
    public const DELIVERY_STATUS_SOFT_BOUNCED = 'soft bounced';
    public const DELIVERY_STATUS_SOFT_BOUNCED___MAILBOX_FULL = 'soft bounced - mailbox full';
    public const DELIVERY_STATUS_HARD_BOUNCED = 'hard bounced';
    public const DELIVERY_STATUS_INTERNAL_ERROR__PLEASE_CHECK_BACK_LATER = 'Internal error. Please check back later.';
    public const DELIVERY_STATUS_DELIVERED = 'delivered';
    public const DELIVERY_STATUS_DELIVERED_VIA_SECURE_PORTAL = 'delivered via secure portal';
    public const OPENED_STATUS_OPENED = 'opened';
    public const OPENED_STATUS_NOT_OPENED = 'not opened';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeliveryStatusAllowableValues()
    {
        return [
            self::DELIVERY_STATUS_PROCESSING,
            self::DELIVERY_STATUS_TLS_NOT_OFFERED_SENDING_VIA_SECURE_PORTAL,
            self::DELIVERY_STATUS_SOFT_BOUNCED,
            self::DELIVERY_STATUS_SOFT_BOUNCED___MAILBOX_FULL,
            self::DELIVERY_STATUS_HARD_BOUNCED,
            self::DELIVERY_STATUS_INTERNAL_ERROR__PLEASE_CHECK_BACK_LATER,
            self::DELIVERY_STATUS_DELIVERED,
            self::DELIVERY_STATUS_DELIVERED_VIA_SECURE_PORTAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOpenedStatusAllowableValues()
    {
        return [
            self::OPENED_STATUS_OPENED,
            self::OPENED_STATUS_NOT_OPENED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('delivery_status', $data ?? [], null);
        $this->setIfExists('delivery_time', $data ?? [], null);
        $this->setIfExists('opened_status', $data ?? [], null);
        $this->setIfExists('opened_time', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['delivery_status'] === null) {
            $invalidProperties[] = "'delivery_status' can't be null";
        }
        $allowedValues = $this->getDeliveryStatusAllowableValues();
        if (!is_null($this->container['delivery_status']) && !in_array($this->container['delivery_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'delivery_status', must be one of '%s'",
                $this->container['delivery_status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOpenedStatusAllowableValues();
        if (!is_null($this->container['opened_status']) && !in_array($this->container['opened_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'opened_status', must be one of '%s'",
                $this->container['opened_status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets delivery_status
     *
     * @return string
     */
    public function getDeliveryStatus()
    {
        return $this->container['delivery_status'];
    }

    /**
     * Sets delivery_status
     *
     * @param string $delivery_status The delivery status of the message
     *
     * @return self
     */
    public function setDeliveryStatus($delivery_status)
    {
        if (is_null($delivery_status)) {
            throw new \InvalidArgumentException('non-nullable delivery_status cannot be null');
        }
        $allowedValues = $this->getDeliveryStatusAllowableValues();
        if (!in_array($delivery_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'delivery_status', must be one of '%s'",
                    $delivery_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['delivery_status'] = $delivery_status;

        return $this;
    }

    /**
     * Gets delivery_time
     *
     * @return string|null
     */
    public function getDeliveryTime()
    {
        return $this->container['delivery_time'];
    }

    /**
     * Sets delivery_time
     *
     * @param string|null $delivery_time The time when the message was delivered (if applicable)
     *
     * @return self
     */
    public function setDeliveryTime($delivery_time)
    {
        if (is_null($delivery_time)) {
            throw new \InvalidArgumentException('non-nullable delivery_time cannot be null');
        }
        $this->container['delivery_time'] = $delivery_time;

        return $this;
    }

    /**
     * Gets opened_status
     *
     * @return string|null
     */
    public function getOpenedStatus()
    {
        return $this->container['opened_status'];
    }

    /**
     * Sets opened_status
     *
     * @param string|null $opened_status Whether the message was opened (single recipient only)
     *
     * @return self
     */
    public function setOpenedStatus($opened_status)
    {
        if (is_null($opened_status)) {
            throw new \InvalidArgumentException('non-nullable opened_status cannot be null');
        }
        $allowedValues = $this->getOpenedStatusAllowableValues();
        if (!in_array($opened_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'opened_status', must be one of '%s'",
                    $opened_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['opened_status'] = $opened_status;

        return $this;
    }

    /**
     * Gets opened_time
     *
     * @return string|null
     */
    public function getOpenedTime()
    {
        return $this->container['opened_time'];
    }

    /**
     * Sets opened_time
     *
     * @param string|null $opened_time The time when the message was first opened (single recipient only)
     *
     * @return self
     */
    public function setOpenedTime($opened_time)
    {
        if (is_null($opened_time)) {
            throw new \InvalidArgumentException('non-nullable opened_time cannot be null');
        }
        $this->container['opened_time'] = $opened_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


