<?php
/**
 * MessageReceiptResponseDataMessage
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Paubox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paubox Email API
 *
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Paubox\Model;

use \ArrayAccess;
use \Paubox\ObjectSerializer;

/**
 * MessageReceiptResponseDataMessage Class Doc Comment
 *
 * @category Class
 * @package  Paubox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MessageReceiptResponseDataMessage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MessageReceiptResponse_data_message';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'message_deliveries' => '\Paubox\Model\MessageDelivery[]',
        'total_opens' => 'int',
        'distinct_opens' => 'int',
        'total_click_count' => 'int',
        'clicks_per_link' => '\Paubox\Model\ClickData[]',
        'unsubscribed' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'message_deliveries' => null,
        'total_opens' => null,
        'distinct_opens' => null,
        'total_click_count' => null,
        'clicks_per_link' => null,
        'unsubscribed' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'message_deliveries' => false,
        'total_opens' => false,
        'distinct_opens' => false,
        'total_click_count' => false,
        'clicks_per_link' => false,
        'unsubscribed' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'message_deliveries' => 'message_deliveries',
        'total_opens' => 'total_opens',
        'distinct_opens' => 'distinct_opens',
        'total_click_count' => 'total_click_count',
        'clicks_per_link' => 'clicks_per_link',
        'unsubscribed' => 'unsubscribed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'message_deliveries' => 'setMessageDeliveries',
        'total_opens' => 'setTotalOpens',
        'distinct_opens' => 'setDistinctOpens',
        'total_click_count' => 'setTotalClickCount',
        'clicks_per_link' => 'setClicksPerLink',
        'unsubscribed' => 'setUnsubscribed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'message_deliveries' => 'getMessageDeliveries',
        'total_opens' => 'getTotalOpens',
        'distinct_opens' => 'getDistinctOpens',
        'total_click_count' => 'getTotalClickCount',
        'clicks_per_link' => 'getClicksPerLink',
        'unsubscribed' => 'getUnsubscribed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('message_deliveries', $data ?? [], null);
        $this->setIfExists('total_opens', $data ?? [], null);
        $this->setIfExists('distinct_opens', $data ?? [], null);
        $this->setIfExists('total_click_count', $data ?? [], null);
        $this->setIfExists('clicks_per_link', $data ?? [], null);
        $this->setIfExists('unsubscribed', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['message_deliveries'] === null) {
            $invalidProperties[] = "'message_deliveries' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The message ID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets message_deliveries
     *
     * @return \Paubox\Model\MessageDelivery[]
     */
    public function getMessageDeliveries()
    {
        return $this->container['message_deliveries'];
    }

    /**
     * Sets message_deliveries
     *
     * @param \Paubox\Model\MessageDelivery[] $message_deliveries message_deliveries
     *
     * @return self
     */
    public function setMessageDeliveries($message_deliveries)
    {
        if (is_null($message_deliveries)) {
            throw new \InvalidArgumentException('non-nullable message_deliveries cannot be null');
        }
        $this->container['message_deliveries'] = $message_deliveries;

        return $this;
    }

    /**
     * Gets total_opens
     *
     * @return int|null
     */
    public function getTotalOpens()
    {
        return $this->container['total_opens'];
    }

    /**
     * Sets total_opens
     *
     * @param int|null $total_opens Total number of opens (single recipient only)
     *
     * @return self
     */
    public function setTotalOpens($total_opens)
    {
        if (is_null($total_opens)) {
            throw new \InvalidArgumentException('non-nullable total_opens cannot be null');
        }
        $this->container['total_opens'] = $total_opens;

        return $this;
    }

    /**
     * Gets distinct_opens
     *
     * @return int|null
     */
    public function getDistinctOpens()
    {
        return $this->container['distinct_opens'];
    }

    /**
     * Sets distinct_opens
     *
     * @param int|null $distinct_opens Number of distinct opens (single recipient only)
     *
     * @return self
     */
    public function setDistinctOpens($distinct_opens)
    {
        if (is_null($distinct_opens)) {
            throw new \InvalidArgumentException('non-nullable distinct_opens cannot be null');
        }
        $this->container['distinct_opens'] = $distinct_opens;

        return $this;
    }

    /**
     * Gets total_click_count
     *
     * @return int|null
     */
    public function getTotalClickCount()
    {
        return $this->container['total_click_count'];
    }

    /**
     * Sets total_click_count
     *
     * @param int|null $total_click_count Total number of clicks (single recipient only)
     *
     * @return self
     */
    public function setTotalClickCount($total_click_count)
    {
        if (is_null($total_click_count)) {
            throw new \InvalidArgumentException('non-nullable total_click_count cannot be null');
        }
        $this->container['total_click_count'] = $total_click_count;

        return $this;
    }

    /**
     * Gets clicks_per_link
     *
     * @return \Paubox\Model\ClickData[]|null
     */
    public function getClicksPerLink()
    {
        return $this->container['clicks_per_link'];
    }

    /**
     * Sets clicks_per_link
     *
     * @param \Paubox\Model\ClickData[]|null $clicks_per_link Click tracking data per link (single recipient only)
     *
     * @return self
     */
    public function setClicksPerLink($clicks_per_link)
    {
        if (is_null($clicks_per_link)) {
            throw new \InvalidArgumentException('non-nullable clicks_per_link cannot be null');
        }
        $this->container['clicks_per_link'] = $clicks_per_link;

        return $this;
    }

    /**
     * Gets unsubscribed
     *
     * @return bool|null
     */
    public function getUnsubscribed()
    {
        return $this->container['unsubscribed'];
    }

    /**
     * Sets unsubscribed
     *
     * @param bool|null $unsubscribed Whether the recipient has unsubscribed (single recipient only)
     *
     * @return self
     */
    public function setUnsubscribed($unsubscribed)
    {
        if (is_null($unsubscribed)) {
            throw new \InvalidArgumentException('non-nullable unsubscribed cannot be null');
        }
        $this->container['unsubscribed'] = $unsubscribed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


