<?php
/**
 * SingleSendResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Paubox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paubox Email API
 *
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Paubox\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SingleSendResponseTest Class Doc Comment
 *
 * @category    Class
 * @description SingleSendResponse
 * @package     Paubox
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SingleSendResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SingleSendResponse"
     */
    public function testSingleSendResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_tracking_id"
     */
    public function testPropertySourceTrackingId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_headers"
     */
    public function testPropertyCustomHeaders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
